import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])
print(x + y, x * y, x / y, x ** y)
x = torch.arange(4)
print(x)
print(x[3])
print(len(x))
print(x.shape)
A = torch.arange(20).reshape(5, 4)
print(A)
print(A.T)
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)
print(B == B.T)
X = torch.arange(24).reshape(2, 3, 4)
print(X)
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
print(A)
print(A + B)
print(A.shape == (A + B).shape)
print(A * B)
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(a + X)
print((a * X).shape)
x = torch.arange(4, dtype=torch.float32)
print(x)
print(x.sum())
print(A.shape)
print(A.sum())
A = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
print(A.shape)
print(A.sum())
print(A)
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0)
print(A_sum_axis0.shape)
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1)
print(A_sum_axis1.shape)
print(A.sum(axis=[0, 1]))
print(A.sum(axis=[0, 1]).shape)
print(A.mean(), A.sum() / A.numel())
print(A.mean(axis=0))
print(A.sum(axis=0) / A.shape[0])
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A)
print(A / sum_A)
print(A)
print(A.cumsum(axis=1))
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x, y, torch.dot(x, y), torch.sum(x * y))
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)
print(A.shape, x.shape, torch.mv(A, x))
B = torch.ones(4, 3)
print(torch.mm(A, B))
u = torch.tensor([4.0, -3.0])
print(torch.norm(u), torch.abs(u).sum(), torch.norm(torch.ones(4, 9)))
